Repository spiceai/spicepy, pull requests merged in 2022-04, with the labels that each got.

#7 Return FlightStreamReader
  README.md
  spicedata/_client.py
Labels: bug

#8 Set min Python to 3.7 and update metadata
  .gitignore
  Makefile
  README.md
  setup.py
  spicedata/__init__.py
  spicedata/_client.py
Labels: bug, enhancement

#9 Fix comma
  setup.py
Labels: bug

#10 Rename folder
  spicepy/__init__.py
  spicepy/_client.py
Labels: bug

#12 Implement test and fix TLS certificate
  spicepy/_client.py
  tests/test_main.py
Labels: bug

#14 Implement lint and github actions
  .flake8
  .github/workflow/lint.yml
  .github/workflows/lint.yml
  .pylintrc
  requirements.txt
  spicepy/__init__.py
Labels: enhancement

#19 Avoid overriding env var for TLS certificate
  spicepy/_client.py
Labels: enhancement
